### PR TITLE
fix: changed tag_type to string

### LINKED ISSUE #260: Tag type needs to change to string 'vlan' from integer 1
There are some compatibility issues with MongoDB and API request JSON format because tag_type is used as a key of a dictionary.

### PR DESCRIPTION
**Pull request by Alopalao**
Closes #260 

### Summary

Tag-type is changed to string
```
    VLAN = 1 to  'vlan'
    VLAN_QINQ = 2 to 'vlan_qinq'
    MPLS = 3 to 'mpls'
```

Update: This change is no longer necessary but it is better to be changing to a string instead of sticking with an integer type value.

### CODE REVIEW

**Review by viniarck — COMMENTED** [review]
@Alopalao looks good, and once again, excellent to have this attribute more higher level as opposed to a number. Since it's breaking the API, can you bump mef_eline v3 on the endpoints? and then when vlan range is delivered then no need to bump again since it's for 2023.2 too.  

Also, did you have the chance to run the entire test suite with your branch?

**Comment by Alopalao** [comment]
> Also, did you have the chance to run the entire test suite with your branch?
Yeah, although new changes have been pushed since then. I am gong to run them again.

**Comment by Alopalao** [comment]
E2E tests are passing with the latest updates:
```
============================= test session starts ==============================
platform linux -- Python 3.9.2, pytest-7.2.0, pluggy-1.3.0
rootdir: /tests
plugins: timeout-2.1.0, rerunfailures-10.2, anyio-3.6.2
collected 241 items

tests/test_e2e_01_kytos_startup.py ..                                    [  0%]
tests/test_e2e_05_topology.py ..................                         [  8%]
tests/test_e2e_10_mef_eline.py ..........ss.....x.....x................  [ 24%]
tests/test_e2e_11_mef_eline.py ......                                    [ 27%]
tests/test_e2e_12_mef_eline.py .....Xx.                                  [ 30%]
tests/test_e2e_13_mef_eline.py .....Xs.s......Xs.s.XXxX.xxxx..X......... [ 47%]
...                                                                      [ 48%]
tests/test_e2e_14_mef_eline.py x                                         [ 49%]
tests/test_e2e_15_mef_eline.py ..                                        [ 50%]
tests/test_e2e_20_flow_manager.py .....................                  [ 58%]
tests/test_e2e_21_flow_manager.py ...                                    [ 60%]
tests/test_e2e_22_flow_manager.py ...............                        [ 66%]
tests/test_e2e_23_flow_manager.py ..............                         [ 72%]
tests/test_e2e_30_of_lldp.py ....                                        [ 73%]
tests/test_e2e_31_of_lldp.py ...                                         [ 75%]
tests/test_e2e_32_of_lldp.py ...                                         [ 76%]
tests/test_e2e_40_sdntrace.py .............                              [ 81%]
tests/test_e2e_41_kytos_auth.py ........                                 [ 85%]
tests/test_e2e_50_maintenance.py ........................                [ 95%]
tests/test_e2e_60_of_multi_table.py .....                                [ 97%]
tests/test_e2e_70_kytos_stats.py .......                                 [100%]
```

**Review by viniarck — APPROVED** [review]
Nicely done, @Alopalao. 

Pre-approving this PR. 

Let's land it as soon as https://github.com/kytos-ng/mef_eline/pull/371 is approved and ready to land too

**Comment by Alopalao** [comment]
New changes for `mef_eline` and `kytos`.
```
============================= test session starts ==============================
platform linux -- Python 3.9.2, pytest-7.2.0, pluggy-1.3.0
rootdir: /tests
plugins: timeout-2.1.0, rerunfailures-10.2, anyio-3.6.2
collected 241 items

tests/test_e2e_01_kytos_startup.py ..                                    [  0%]
tests/test_e2e_05_topology.py ..................                         [  8%]
tests/test_e2e_10_mef_eline.py ..........ss.....x.....x................  [ 24%]
tests/test_e2e_11_mef_eline.py ......                                    [ 27%]
tests/test_e2e_12_mef_eline.py .....Xx.                                  [ 30%]
tests/test_e2e_13_mef_eline.py ....FXs.s.....FXs.s.XXxX.xxxx..X......... [ 47%]
...                                                                      [ 48%]
tests/test_e2e_14_mef_eline.py x                                         [ 49%]
tests/test_e2e_15_mef_eline.py ..                                        [ 50%]
tests/test_e2e_20_flow_manager.py .....................                  [ 58%]
tests/test_e2e_21_flow_manager.py ...                                    [ 60%]
tests/test_e2e_22_flow_manager.py ...............                        [ 66%]
tests/test_e2e_23_flow_manager.py ..............                         [ 72%]
tests/test_e2e_30_of_lldp.py ....                                        [ 73%]
tests/test_e2e_31_of_lldp.py ...                                         [ 75%]
tests/test_e2e_32_of_lldp.py ...                                         [ 76%]
tests/test_e2e_40_sdntrace.py .............                              [ 81%]
tests/test_e2e_41_kytos_auth.py ........                                 [ 85%]
tests/test_e2e_50_maintenance.py ........................                [ 95%]
tests/test_e2e_60_of_multi_table.py .....                                [ 97%]
tests/test_e2e_70_kytos_stats.py .......                                 [100%]
```
Failures were from `test_025_patch_an_inconsistent_uni_a()` and `test_075_patch_an_inconsistent_uni_z()` which are now deleted since they tested for the wrong type of value of `tag_type` but now we support both integer and string.

**Review by viniarck — COMMENTED** [review]
@Alopalao appreciated the updates and the refactoring. 

Since we ended up still supporting `"tag_type": 1`, could you try to still use the `"tag_type: 1"` value for creation and update, just so we still have e2e cov for this type too? We probably don't want to paratrize both for all tests since e2e tend to be a bit slow, but it'd be great to find a balance and cover a few essential ones with this type too.

**Review by viniarck — APPROVED** [review]
LGTM. Nicely done. 

Let's ship this once the depending PRs are also approved and ready to land. Once mef_eline PR is ready https://github.com/kytos-ng/mef_eline/pull/371 then this can get merged into master.

**Pull request merged**
